"""
Constantes centrales de l'application.

Ce module contient toutes les constantes utilisées dans l'application, incluant les codes de statut
HTTP, les valeurs par défaut et les seuils.
"""

# Codes de statut HTTP
HTTP_STATUS_OK = 200
HTTP_STATUS_CREATED = 201
HTTP_STATUS_BAD_REQUEST = 400
HTTP_STATUS_UNAUTHORIZED = 401
HTTP_STATUS_FORBIDDEN = 403
HTTP_STATUS_NOT_FOUND = 404
HTTP_STATUS_CONFLICT = 409
HTTP_STATUS_TOO_MANY_REQUESTS = 429
HTTP_STATUS_INTERNAL_SERVER_ERROR = 500
HTTP_STATUS_BAD_GATEWAY = 502
HTTP_STATUS_UNPROCESSABLE_ENTITY = 422

# Plages de codes de statut HTTP
HTTP_STATUS_SUCCESS_MIN = 200
HTTP_STATUS_SUCCESS_MAX = 299
HTTP_STATUS_CLIENT_ERROR_MIN = 400
HTTP_STATUS_CLIENT_ERROR_MAX = 499
HTTP_STATUS_SERVER_ERROR_MIN = 500
HTTP_STATUS_SERVER_ERROR_MAX = 599

# Limites de validation
MAX_TOP_K = 50
MIN_TOP_K = 1
MAX_RETRY_ATTEMPTS = 3

# Seuils de coût et budget
COST_WARNING_THRESHOLD = 0.8
COST_BLOCK_THRESHOLD = 1.0
BUDGET_MAX_PERCENTAGE = 100.0

# Formats et longueurs
UUID_LENGTH = 36
SHA256_HEX_LENGTH = 64
DATE_FORMAT_LENGTH = 7  # YYYY-MM format

# Valeurs par défaut pour les tests et benchmarks
DEFAULT_QPS = 50
DEFAULT_TENANTS = 3
DEFAULT_DURATION = 300
DEFAULT_TOPK = 10
DEFAULT_CHUNK_SIZE = 512
DEFAULT_PRECISION_SCORE_MAX = 5

# Seuils de précision pour les tests
TEST_PRECISION_TOLERANCE = 0.001
TEST_PRECISION_TOLERANCE_SMALL = 0.01

# Valeurs pour les métriques et calculs
NDCG_MIN_THRESHOLD = 0.7
NDCG_MAX_THRESHOLD = 0.99
NDCG_DISJOINT_THRESHOLD = 0.05
TUPLE_LENGTH = 2

# Valeurs pour les retry et backoff
RETRY_BASE_DELAY = 0.1
RETRY_RANDOM_FACTOR = 0.05

# Valeurs pour les scripts
SCRIPT_PREVIEW_LIMIT = 12
SCRIPT_DATE_FORMAT_LENGTH = 7  # YYYY-MM format
SCRIPT_SLO_BREACH_THRESHOLD_1H = 2.0
SCRIPT_SLO_BREACH_THRESHOLD_6H = 1.0
SCRIPT_BUDGET_MAX_PERCENTAGE = 100.0
SCRIPT_UUID_LENGTH = 36
SCRIPT_SHA256_HEX_LENGTH = 64

# Valeurs pour les tests
TEST_HTTP_STATUS_OK = 200
TEST_HTTP_STATUS_CREATED = 201
TEST_HTTP_STATUS_BAD_REQUEST = 400
TEST_HTTP_STATUS_UNAUTHORIZED = 401
TEST_HTTP_STATUS_FORBIDDEN = 403
TEST_HTTP_STATUS_NOT_FOUND = 404
TEST_HTTP_STATUS_CONFLICT = 409
TEST_HTTP_STATUS_TOO_MANY_REQUESTS = 429
TEST_HTTP_STATUS_INTERNAL_SERVER_ERROR = 500
TEST_HTTP_STATUS_BAD_GATEWAY = 502
TEST_HTTP_STATUS_UNPROCESSABLE_ENTITY = 422

# Valeurs pour les benchmarks et tests de performance
TEST_DEFAULT_QPS = 50
TEST_DEFAULT_TENANTS = 3
TEST_DEFAULT_DURATION = 300
TEST_DEFAULT_TOPK = 10
TEST_DEFAULT_CHUNK_SIZE = 512
TEST_DEFAULT_PRECISION_SCORE_MAX = 5
TEST_BENCHMARK_QPS = 100
TEST_BENCHMARK_TENANTS = 5
TEST_BENCHMARK_DURATION = 600
TEST_BENCHMARK_TOPK = 20
TEST_BENCHMARK_CHUNK_SIZE = 1024
TEST_BENCHMARK_WARMUP_REQUESTS = 5
TEST_BENCHMARK_TOTAL_REQUESTS = 10
TEST_BENCHMARK_EXPECTED_REQUESTS = 6
TEST_BENCHMARK_TENANT_COUNT = 2
TEST_BENCHMARK_TENANT_REQUESTS = 5
TEST_BENCHMARK_CALL_COUNT = 15
TEST_BENCHMARK_CALL_COUNT_LOG = 2

# Valeurs pour les tests de métriques
TEST_METRICS_PRECISION_TOLERANCE = 0.001
TEST_METRICS_PRECISION_TOLERANCE_SMALL = 0.01
TEST_METRICS_NDCG_MIN = 0.7
TEST_METRICS_NDCG_MAX = 0.99
TEST_METRICS_NDCG_DISJOINT = 0.05
TEST_METRICS_COST_THRESHOLD = 8.0
TEST_METRICS_SHADOW_SAMPLE_RATE = 0.5
TEST_METRICS_MAX_INPUT_LEN = 7

# Valeurs pour les tests de longueur et format
TEST_UUID_LENGTH = 36
TEST_SHA256_HEX_LENGTH = 64
TEST_DATE_FORMAT_LENGTH = 7
TEST_PRECISION_SCORE_MIN = 1
TEST_PRECISION_SCORE_MAX = 5
