name: Alembic Migrate

on:
  push:
    branches:
      - feat/7-contentversion-sql
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Alembic upgrade
        env:
          DATABASE_URL: sqlite:///./cv.db
          PYTHONPATH: .
        run: |
          alembic upgrade head
          test -f cv.db
