name: PR Image Build (no push)

on:
  pull_request:
    branches: [ "main", "develop", "release/**" ]
    paths:
      - "docker/**"
      - "Dockerfile"
      - "**/Dockerfile"
      - ".github/workflows/pr_image_build.yml"
      - "backend/**"
  workflow_dispatch:
    inputs:
      trivy_mode:
        description: "scan mode: warn|strict"
        required: false
        default: "strict"

permissions:
  contents: read

env:
  IMAGE_NAME: pr-check
  # change to "strict" pour bloquer sur vulnérabilités HIGH+
  TRIVY_MODE: ${{ github.event.inputs.trivy_mode || 'strict' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (no push) with cache
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: false
          load: true
          tags: ${{ env.IMAGE_NAME }}:pr-${{ github.event.pull_request.number || github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Show image size
        run: |
          docker image ls $IMAGE_NAME:pr-${{ github.event.pull_request.number || github.run_number }}

      - name: Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./docker/Dockerfile
          config: ./hadolint.yaml

      - name: Trivy FS scan (workspace)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          ignore-unfixed: true
          format: 'table'
          exit-code: ${{ env.TRIVY_MODE == 'strict' && '1' || '0' }}
          severity: 'HIGH,CRITICAL'

      - name: Trivy Image scan (built image)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:pr-${{ github.event.pull_request.number || github.run_number }}
          ignore-unfixed: true
          format: 'table'
          exit-code: ${{ env.TRIVY_MODE == 'strict' && '1' || '0' }}
          severity: 'HIGH,CRITICAL'

      - name: Generate SBOM (CycloneDX)
        run: |
          trivy image --format cyclonedx --output sbom.cdx.json $IMAGE_NAME:pr-${{ github.event.pull_request.number || github.run_number }} || true

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-cyclonedx
          path: sbom.cdx.json
          if-no-files-found: ignore

      - name: Gitleaks (secrets scan)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: detect --source=. --no-git -v --redact --exit-code 1

      - name: Compile & Ruff & Pytest (smoke rapide)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m compileall -q backend
          ruff check backend --output-format=github
          ruff format --check backend
          pytest -q
