name: Release

on:
  release:
    types: [published]

permissions:
  id-token: write      # for keyless signing
  contents: read
  packages: write      # to push to GHCR

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-push-sign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Install cosign
        uses: sigstore/cosign-installer@v3.7.0
      - name: Sign container image (keyless)
        env:
          COSIGN_EXPERIMENTAL: '1'
        run: |
          DIGEST=$(echo '${{ steps.build-and-push.outputs.digest }}')
          cosign sign ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${DIGEST}

