name: SLO Monthly Report

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:
    inputs:
      report_month:
        description: "YYYY-MM (optional)"
        required: false
        default: ""

jobs:
  build-report:
    runs-on: ubuntu-latest
    env:
      PROM_QUERY_URL: ${{ secrets.PROM_QUERY_URL || '' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Fetch LLM budget MTD from Prometheus
        if: env.PROM_QUERY_URL != ''
        id: llm_budget
        run: |
          val=$(curl -s -G "$PROM_QUERY_URL/api/v1/query" \
            --data-urlencode 'query=increase(llm_cost_usd_total[30d])' \
            | jq -r '.data.result[0].value[1]' || echo "0")
          echo "LLM_BUDGET_MTD=$val" >> $GITHUB_ENV
      - name: Debug LLM_BUDGET_MTD
        run: |
          echo "::add-mask::$LLM_BUDGET_MTD"
          echo "LLM_BUDGET_MTD=$LLM_BUDGET_MTD"
      - name: Generate SLO report
        env:
          GRAFANA_DASHBOARD_URL: ${{ secrets.GRAFANA_DASHBOARD_URL || '' }}
        run: |
          python -m pip install --upgrade pip
          MONTH_ARG=""
          if [ -n "${{ github.event.inputs.report_month }}" ]; then MONTH_ARG="--month ${{ github.event.inputs.report_month }}"; fi
          python -m scripts.slo_report --output-dir artifacts/slo $MONTH_ARG
      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: slo-report
          path: artifacts/slo/*.md
          if-no-files-found: warn
